
export const SET_PICKER_COLOR = 'SET_PICKER_COLOR';

export const SET_COLOR_REQUESTED = 'SET_COLOR_REQUESTED';
export const SET_COLOR_ERROR = 'SET_COLOR_ERROR';
export const SET_COLOR_SUCCESS = 'SET_COLOR_SUCCESS';

export const REQUEST_PLACE = 'REQUEST_PLACE';
export const LOAD_PLACE_ERROR = 'LOAD_PLACE_ERROR';
export const LOAD_PLACE_SUCCESS = 'LOAD_PLACE_SUCCESS';

export const UPDATE_TIMEOUT = 'UPDATE_TIMEOUT';

export const SELECT_PIXEL = 'SELECT_PIXEL';

export const PIXEL_UPDATED = 'PIXEL_UPDATED';

export const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
export const LOAD_TIMEOUT_SUCCESS = 'LOAD_TIMEOUT_SUCCESS';
