version: '3'
services:
  redis:
    image: "redis"
    hostname: redis
    ports:
     - 6379
  rabbitmq:
    image: "rabbitmq:management"
    hostname: rabbitmq
    ports:
     - 5672
     - 15672
    volumes:
     - /var/lib/rabbitmq:/var/lib/rabbitmq
  backend:
    image: "192.168.2.136:5000/backend"
    ports:
     - 2222
    environment:
     TARGET_HOST_REDIS: redis
     TARGET_HOST_RABBITMQ: rabbitmq
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
  bot:
    image: "192.168.2.136:5000/bot"
    environment:
     TARGET_HOST_BACKEND: backend
     BOT_CONFIG: QUICK_TEST
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
