version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.0"
    ports:
     - 9200:9200

  logstash:
    image: "docker.elastic.co/logstash/logstash:5.4.0"
    ports:
     - 12201:12201/udp
    volumes:
     - /var/lib/logstash:/config-dir
    command: ["logstash", "-f", "/config-dir/logstash.conf"]
    deploy:
      mode: global

  kibana:
    image: "docker.elastic.co/kibana/kibana:5.4.0"
    ports:
     - 5601:5601
    deploy:
      mode: global

