version: '3'
services:
  redis:
    image: "redis"
    hostname: redis
    ports:
     - 6379:6379
  rabbitmq:
    image: "rabbitmq:management"
    hostname: rabbitmq
    ports:
     - 5672:5672
     - 15672:15672
    volumes:
     - /var/lib/rabbitmq:/var/lib/rabbitmq
  backend1:
    build: backend
    links:
     - redis
     - rabbitmq
    ports:
     - 2222
    environment:
     TARGET_HOST_REDIS: redis
     TARGET_HOST_RABBITMQ: rabbitmq
  backend2:
    build: backend
    links:
     - redis
     - rabbitmq
    ports:
     - 2222
    environment:
     TARGET_HOST_REDIS: redis
     TARGET_HOST_RABBITMQ: rabbitmq
  bot1:
    build: bot
    links:
     - backend1:backend
    environment:
     TARGET_HOST_BACKEND: backend
     BOT_CONFIG: QUICK_TEST
  bot2:
    build: bot
    links:
     - backend2:backend
    environment:
     TARGET_HOST_BACKEND: backend
     BOT_CONFIG: QUICK_TEST
