version: '3'
services:
  redis:
    image: "redis"
    hostname: redis
    ports:
     - 6379
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "redis"
  rabbitmq:
    image: "rabbitmq:management"
    hostname: rabbitmq
    ports:
     - 5672
     - 15672
    volumes:
     - /var/lib/rabbitmq:/var/lib/rabbitmq
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rabbitmq"
  backend:
    image: "192.168.2.136:5000/backend"
    ports:
     - 2222
    environment:
     TARGET_HOST_REDIS: redis
     TARGET_HOST_RABBITMQ: rabbitmq
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: backend
  frontend:
    image: "192.168.2.136:5000/frontend"
    ports:
     - 80
    environment:
     TARGET_HOST_BACKEND: backend
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: frontend
  bot:
    image: "192.168.2.136:5000/bot"
    environment:
     TARGET_HOST_BACKEND: backend
     BOT_CONFIG: QUICK_TEST
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: on-failure
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: bot
