version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.0"
    ports:
     - 9200:9200

  logstash:
    image: "192.168.2.136:5000/logstash"
    ports:
     - 12201:12201/udp
    deploy:
      mode: global

  kibana:
    image: "docker.elastic.co/kibana/kibana:5.4.0"
    ports:
     - 5601:5601
    environment:
      XPACK_SECURITY_ENABLED: "false"
      XPACK_SECURITY_SESSIONTIMEOUT: 36000000 #10 Hours = 36000 seconds = 36_000_000 milliseconds
    deploy:
      mode: global

