version: '3'
services:
  graphite:
    image: "hopsoft/graphite-statsd"
    hostname: graphite
    ports:
     - 8888:80
     - 2003:2003
    volumes:
     - ./data/graphite/conf:/opt/graphite/conf
     - ./data/graphite/storage:/opt/graphite/storage
  grafana:
    image: "grafana-patch"
    hostname: grafana
    ports:
     - 80:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    links:
     - graphite